### ISSUE TITLE
Cache timezones

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/davis-server#121]
The timezone list is unlikely to change.  Therefore, we should only make the call once and keep it in browser memory.

**Comment by dyladan** [comment]
if we are going to be storing it in memory anyways why not just compile the list into the code?

```
timezones = require('../../../../../lib/config/timezones')
```

**Comment by dyladan** [comment]
I was able to quickly mock this out and make sure it works by doing this:

In `web/src/app/shared/config/config.service.ts` add this line at the top:

```
const timezones = require('./../../../../../lib/config/timezones');
```

And modified getTimezones to look like this

```
getTimezones(): Promise<any> {
  return Promise.resolve({ success: true, timezones });
}
```

It makes it so no other code changes are required but it definitely makes excessive use of promises since we're no longer making a http request. Would be better to have getTimezones return the list and modify whatever code calls it to handle a list rather than a promise. Anyways hopefully this is a good starting point.
